### GET /users/:id/reviews
GET http://localhost:5000/users/5/reviews

### GET /users/reviews
GET http://localhost:5000/users/reviews

### GET /hotels
GET http://localhost:5000/hotels

### GET /hotels/:id
GET http://localhost:5000/hotels/3

### GET /hotels/reviews
GET http://localhost:5000/hotels/reviews